insecure: false
port: 5000
url: http://httpbingo.org
verbosity: 3
modifiers: |-
  # GET
  - method.Filter:
      method: GET
      modifier:
        fifo.Group:
          modifiers:
            - url.Filter:
                path: /headers/:version/:file
                modifier:
                  fifo.Group:
                    modifiers:
                      - url.Modifier:
                          scope: [request]
                          path: /headers/:file/:version
