name: goreleaser

on:
  push:
    branches:
      - "master"
    tags:
      - v*.*.*

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.5
      - name: Registry Login
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: |
          echo $GHCR_PAT | docker login ghcr.io --username $GITHUB_ACTOR --password-stdin
      - name: Snapshot
        if: "!startsWith(github.ref, 'refs/tags/v')"
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
